export const routers = {
  HOME: "HOME",
  LOGIN: "LOGIN",
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE",
  LOGTIME_HISTORY: "LOGTIME_HISTORY",
  WELCOME: "WELCOME",
  PERMISSIONS: "PERMISSIONS",
  FACE_RECOGNIZE: "FACE_RECOGNIZE"
};
